image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: |
      cachix use haskell-language-server
      nix-shell
      cabal update
      cabal build
